version: '3.8'
services:
  compras-service:
    build: ./compras-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - producto-service
      - proveedor-service
      - inventario-service
  inventario-service:
    build: ./inventario-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  producto-service:
    build: ./producto-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  proveedor-service:
    build: ./proveedor-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - compras-service
      - inventario-service
      - producto-service
      - proveedor-service
